name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST "https://api.render.com/deploy/srv-d648nma4d50c73e84dd0?key=${{ secrets.RENDER_DEPLOY_HOOK_KEY }}"
